
services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: graphql_recipe_management_web
    volumes:
        - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: